const express = require("express");
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
const userRoutes = require("./routes/user-routes");
const adminRoutes = require("./routes/admin-routes");
const productRoutes = require("./routes/product-routes");
const favoriteRoutes = require("./routes/favorite-routes");
const categoryRoutes = require("./routes/category-routes");
const cardRoutes = require("./routes/card-routes");
const orderRoutes = require("./routes/order-routes");
app.use("/user", userRoutes);
app.use("/admin", adminRoutes);
app.use("/product", productRoutes);
app.use("/favorite", favoriteRoutes);
app.use("/category", categoryRoutes);
app.use("/card", cardRoutes);
app.use("/order", orderRoutes);
module.exports = app;
